/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#0b1d2b',
        'surface-container': '#e2efff',
        'tertiary-fixed': '#cbe6ff',
        'primary': '#b3272e',
        'secondary-fixed': '#ffddb3',
        'on-primary-fixed-variant': '#910619',
        'error': '#ba1a1a',
        'primary-fixed': '#ffdad7',
        'primary-fixed-dim': '#ffb3af',
        'surface-dim': '#cadcf0',
        'surface-container-low': '#ecf4ff',
        'tertiary-container': '#249de2',
        'primary-container': '#ff5e5e',
        'on-secondary-container': '#704800',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9ff',
        'surface-container-high': '#d8eafe',
        'on-secondary-fixed-variant': '#633f00',
        'on-background': '#0b1d2b',
        'on-primary-fixed': '#410005',
        'secondary-fixed-dim': '#ffb950',
        'inverse-on-surface': '#e7f2ff',
        'surface-variant': '#d2e4f8',
        'tertiary-fixed-dim': '#8fcdff',
        'on-tertiary-fixed-variant': '#004b71',
        'surface': '#f7f9ff',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#5a413f',
        'outline': '#8e706e',
        'on-tertiary-container': '#00314c',
        'on-tertiary-fixed': '#001e30',
        'secondary-container': '#fdb64a',
        'on-primary': '#ffffff',
        'surface-tint': '#b3272e',
        'on-primary-container': '#63000c',
        'inverse-primary': '#ffb3af',
        'secondary': '#825500',
        'tertiary': '#006495',
        'background': '#f7f9ff',
        'outline-variant': '#e2bebc',
        'on-secondary-fixed': '#291800',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#213241',
        'surface-container-highest': '#d2e4f8',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '20px',
        'stack-gap-lg': '24px',
        'card-padding': '16px',
        'stack-gap-md': '16px',
        'stack-gap-sm': '8px',
        'inline-gap': '12px',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
